### PR TITLE
Fix misplacement on tap, hatch marks disappearing and make small lines configurable

### PR DESCRIPTION
**Pull request by felixgabler**
I made a few fixes because we need them for our project. Perhaps you find them useful, otherwise feel free to disregard this PR. Sorry for not splitting it up more! If you want me to open sub-PRs for the different issues, let me know.

1. This fixes the misplacement issue where the handler does not respect the steps when you start the drag in the trackbar or just tap between lines. Now, it makes sure it aligns with the lines.
2. Before, when the `handlerSize` is similar in size to the constraints of the track bar container, the lines will disappear. This is because the wrong constraints are used (`max` instead of `min`)
3. It is now possible to specify how many small lines should be drawn between any two big lines

### CODE REVIEW

**Comment by loonix** [comment]
looks like a small change. let me test it first then I'll merge it if its all good

**Comment by loonix** [comment]
Hi,

This is the example we have on the source:
image

With your code changes:
image

Please review your code so that all scenarios work.

**Review by loonix — CHANGES_REQUESTED** [review]
Please check your changes against the example. When they are all working then I will review your changes.

**Comment by felixgabler** [comment]
Hi, sorry for not checking the example app earlier. I've pushed a fix but there are definitely still changes. My issue before was that when supplying a handlerSize, the container height had to be at least twice that for some reason. One result of this is that when I tried to build a slider with height 50 where the handler has a height of 45, it would completely remove some parts of the slider since the slider believes it needs to be of height 2*45=90, i.e. layed out completely differently.

My latest changes make sure this does not happen but then again it could also be a breaking change for anyone using the library rn. How do you wish to proceed?

**Review by loonix — CHANGES_REQUESTED** [review]
this still breaks the range slider. If there are breaking changes please update the example, so I can see what changes and also to see if it is worth to make this change.

**Comment by felixgabler** [comment]
I will split up the PR into multiple PRs because I unfortunately don't quite have the time to fix the size issue. This way, the other changes can at least become part of the code.

**Pull request closed without merging**
